# Site settings
title: World of Piggy
email: worldofpiggy@gmail.com
url: http://worldofpiggy.com
description: "Thinking human world in mathematical terms. Applied math and data science to every day problems."
skills: "Data Scientist, Software Engineer, and Code Artist"
meta_author: Gadaleta Francesco

# Publication date
#time: 2011-12-01 
lang: en-us

# podcast info
podcast:
  title: Data Science at Home
  subtitle: podcast subtitle
  url: podcast
  description: podcast description 
  author: Francesco Gadaleta
  copyright:  "&#x2117; &amp; &#xA9; 2016"
  keywords: [data science, big data, predictive, analytics]
  explicit: clean

# Google webmaster tools
google_verify: 

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# tags are linked
link-tags: true


# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus: worldofpiggy
#disqus_shortname: worldofpiggy    #this is used in js_disqus (which we do not use)

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 437aab #2692d2  #18bc9c #80B3FF   
  text: 434550
  primary-rgb: "67,122,171" #"128,179,255"
  secondary: 233140 #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 10
paginate_path: "/blog/page:num/"

# Footer settings
footer:
  copyright: worldofpiggy.com
  location: World
  social: Social
  credits: Credits  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/worldofpiggy
  - title: github
    url: http://github.com/worldofpiggy
  - title: linkedin 
    url: http://www.linkedin.com/in/fragadaleta 

author: Francesco Gadaleta

# Postal address (add as many lines as necessary)
address:
  - line: Blog
    url: /blog
  - line: Podcast
    url: /podcast
  - line: Services
    url: /services
  - line: About
    url: /about

    
# Credits content
credits:
  - line: 'Copyright (c) 2016'
  - line: 'worldofpiggy.com'
  

# Build settings
markdown: kramdown
permalink: pretty

gems:
  - jekyll-paginate
